#!/bin/bash
init=("pipewire" "wireplumber" "mpd" "yambar")
for p in "${!init[@]}"; do
  if ! pgrep -x ${init[$p]} >> /dev/null; then
    sh -c ${init[$p]} &
    sleep 2
  else
    echo "info: did not run ${init[$p]}"
  fi
done
