text: &text Source Code Pro:size=14
icon_big: &icon_big Font Awesome 6 Free Solid:style=Solid:size=12
underline: &underline {underline: { size: 1, color: 455574FF}}
bar:
  height: 31 
  location: top
  spacing: 16
  margin: 8
  font: *text 
  foreground: B3C4E0FF
  background: 0E0B16FF
  border:
    bottom-width: 1
    color: 455574FF
  left:
    - i3:
        sort: ascending
        anchors: 
          - string: &i3_common {margin: 10, on-click: "swaymsg --quiet workspace {name}"}
          - string: &default {<<: *i3_common, text: "{name}"}
          - focused: &focused
              deco: {stack: [ *underline]}
          - invisible: &invisible {foreground: F9F9F9FF}
          - urgent: &urgent
              foreground: 6C7D9CFF
              deco: {stack: [background: {color: 10E080FF}, <<:  *underline]}
          - map: &i3_mode
              default:
                - string:
                    margin: 5
                    text: "{mode}"
                    deco: {background: {color: 10E080FF}}
                - empty: {right-margin: 7}
              conditions:
                mode == default: {empty: {}}
        content:
          "":
            map:
              conditions:
                state == focused:   {string: {<<: [*default, *focused]}}
                state == unfocused: {string: {<<: *default}}
                state == invisible: {string: {<<: [*default, *invisible]}}
                state == urgent:    {string: {<<: [*default, *urgent]}}
  right:
    - network:
        name: wlp1s0
        poll-interval: 1000
        content:
          map:
            default: {string: {text:  , font: *icon_big, foreground: F9F9F9FF}}
            conditions:
        # SOLVE: add a more representative icon
              state == down: {string: {text:  , font: *icon_big, foreground: B30039FF}}
              state == up:
        # SOLVE: add color change based on signal quality
                - string: {text: "{ssid}",right-margin: 5}
                - string: {text:  ,font: *icon_big}
    - pipewire:
        anchors:
          volume: &volume
            conditions:
              muted: {string: {text: "{cubic_volume}%"}}
              ~muted: {string: {text: "{cubic_volume}%"}}
        content:
          list:
            items:
              - map:
                  conditions:
                    type == "sink":
                      - ramp:
                          tag: cubic_volume
                          items:
                            - string: {text:   ,font: *icon_big}
                            - string: {text:   ,font: *icon_big}
                            - string: {text:   ,font: *icon_big}
                    type == "source":
                      map:
                        conditions:
                          muted: {string: {text:  ,font: *icon_big}}
                          ~muted: {string: {text:  ,font: *icon_big}}
              - map:
                  <<: *volume
    - cpu:
        content:
          map:
            conditions:
              id < 0:
                - string: {text: "{cpu}%",right-margin: 5}
                - string: {text:  , font: *icon_big}
    - mem:
          interval: 1500
          content:
            - string: {text: "{used:mb} MB",right-margin: 5}
            - string: {text:  ,font: *icon_big}
    - backlight:
        name: amdgpu_bl0
        content: 
          - string: {text: "{percent}%",right-margin: 5}
          - ramp:
              tag: brightness
              items:
                - string: {text: n , foreground: B30039FF, font: *icon_big}
                - string: {text: l , foreground: E69200FF, font: *icon_big}
                - string: {text: m , foreground: 32ED4FFF, font: *icon_big} 
                - string: {text:  , foreground: 32ED4FFF, font: *icon_big} 
    - battery:
        name: BAT0
        poll-interval: 30
        anchors:
          discharging: &discharging
            list:
              items:
                - string: {text: "{capacity}%",right-margin: 5}
                - ramp:
                    tag: capacity
                    items:
                      - string: {text:  , foreground: B30039FF, font: *icon_big}
                      - string: {text:  , foreground: E69200FF, font: *icon_big}
                      - string: {text:  , foreground: 32ED4FFF, font: *icon_big} 
                      - string: {text:  , foreground: 32ED4FFF, font: *icon_big} 
                      - string: {text:  , foreground: 32ED4FFF, font: *icon_big} 
                      - string: {text:  , foreground: 32ED4FFF, font: *icon_big} 
                      - string: {text:  , foreground: 32ED4FFF, font: *icon_big} 
                      - string: {text:  , foreground: 32ED4FFF, font: *icon_big} 
                      - string: {text:  , foreground: 32ED4FFF, font: *icon_big} 
                      - string: {text:  , foreground: 32ED4FFF, font: *icon_big}
        content:
          map:
            conditions:
              state == unknown:
                <<: *discharging
              state == discharging:
                <<: *discharging
              state == charging:
                - string: {text: "{capacity}%",right-margin: 5}
                - string: {text:  , font: *icon_big}
              state == full:
                - string: {text: "{capacity}%",right-margin: 5}
                - string: {text:  , font: *icon_big}
    - clock:
        time-format: "%H:%M"
        content:
          - string: {text: "{date}",right-margin: 5}
          - string: {text:  , font: *icon_big,right-margin: 32}
          - string: {text: "{time}",right-margin: 5}
          - string: {text:  , font: *icon_big,right-margin: 10}
