text: &text Source Code Pro:size=14
icon: &icon Overpass Nerd Font:style=Solid:size=16
underline: &underline {underline: { size: 1, color: 455574FF}}
bar:
  height: 29 
  location: top
  spacing: 8
  margin: 4
  font: *text 
  foreground: B3C4E0FF
  background: 0E0B16FF
  border:
    bottom-width: 1
    color: 455574FF
  left:
    - i3:
        sort: ascending
        strip-workspace-numbers: true
        anchors:
          - string: &i3_common {margin: 10, on-click: "swaymsg --quiet workspace {name}"}
          - string: &default {<<: *i3_common, text: "{name}",font: *icon}
          - focused: &focused
              deco: {stack: [ *underline]}
          - invisible: &invisible {foreground: F9F9F9FF}
          - urgent: &urgent
              foreground: 6C7D9CFF
              deco: {stack: [background: {color: 10E080FF}, <<:  *underline]}
          - map: &i3_mode
              defaut:
                - string:
                    margin: 5
                    text: "{mode}"
                    deco: {background: {color: 10E080FF}}
                - empty: {right-margin: 7}
              conditions:
                mode == default: {empty: {}}
                mode == resize: {string: {text: "pogger"}}
                mode == capture: {string: {text: "noogger"}}
        content:
          "":
            map:
              conditions:
                state == focused:   {string: {<<: [*default, *focused]}}
                state == unfocused: {string: {<<: *default}}
                state == invisible: {string: {<<: [*default, *invisible]}}
                state == urgent:    {string: {<<: [*default, *urgent]}}
    - mpd:
        host: 127.0.0.1
        port: 6600
        content:
          - string: {text: "{title} {pos}/{end}",right-margin: 5}
  right:
    - network:
        name: wlp1s0
        poll-interval: 1000
        content:
          map:
            default: {string: {text:  , font: *icon, foreground: F9F9F9FF}}
            conditions:
              state == down: {string: {text: 󰖪 , font: *icon}}
              state == up:
                - string: {text: "{ssid}",right-margin: 5}
                - string: {text:  ,font: *icon}
    - pipewire:
        anchors:
          volume: &volume
            conditions:
              muted: {string: {text: " {cubic_volume}%",right-margin: 5}}
              ~muted: {string: {text: " {cubic_volume}%",right-margin: 5}}
        content:
          list:
            items:
              - map:
                  <<: *volume
              - map:
                  on-click: "foot -a mixer pulsemixer"
                  conditions:
                    type == "sink":
                      map:
                        conditions:
                          muted: {string: {text: 󰝟 ,font: *icon}}
                          ~muted: 
                            - ramp:
                                tag: cubic_volume
                                items:
                                  - string: {text:   ,font: *icon}
                                  - string: {text:   ,font: *icon}
                                  - string: {text:   ,font: *icon}
                    type == "source":
                      map:
                        conditions:
                          muted: {string: {text:  ,font: *icon}}
                          ~muted: {string: {text:  ,font: *icon}}
    - cpu:
        content:
          map:
            conditions:
              id < 0:
                - string: {text: "{cpu}%",right-margin: 5}
                - string: {text:  , font: *icon}
    - mem:
          interval: 1500
          content:
            - string: {text: "{used:mb} MB",right-margin: 5}
            - string: {text:  ,font: *icon}
    - backlight:
        name: amdgpu_bl0
        content: 
          - string: {text: "{percent}%",right-margin: 5}
          - ramp:
              tag: brightness
              items:
                - string: {text:  , font: *icon}
                - string: {text: 󱎖 , font: *icon} 
                - string: {text:  , font: *icon} 
    - battery:
        name: BAT0
        poll-interval: 30
        anchors:
          discharging: &discharging
            list:
              items:
                - string: {text: "{capacity}%",right-margin: 5}
                - ramp:
                    tag: capacity
                    items:
                      - string: {text:  , font: *icon}
                      - string: {text:  , font: *icon}
                      - string: {text:  , font: *icon} 
                      - string: {text:  , font: *icon} 
                      - string: {text:  , font: *icon} 
                      - string: {text:  , font: *icon} 
                      - string: {text:  , font: *icon} 
                      - string: {text:  , font: *icon} 
                      - string: {text:  , font: *icon} 
                      - string: {text:  , font: *icon}
        content:
          map:
            conditions:
              state == unknown:
                <<: *discharging
              state == discharging:
                <<: *discharging
              state == charging:
                - string: {text: "{capacity}%",right-margin: 5}
                - string: {text:  , font: *icon}
              state == full:
                - string: {text: "{capacity}%",right-margin: 5}
                - string: {text:  , font: *icon}
              state == "not charging":
                <<: *discharging
    - clock:
        time-format: "%H:%M"
        content:
          - string: {text: "{date}",right-margin: 5}
          - string: {text:  , font: *icon,right-margin: 12}
          - string: {text: "{time}",right-margin: 5}
          - string: {text:  , font: *icon,right-margin: 6}
