text: &text Source Code Pro:size=13
icon: &icon Overpass Nerd Font:style=Solid:size=15
bar:
  height: 25 
  location: top
  spacing: 6
  margin: 5
  font: *text 
  foreground: B3C4E0FF
  background: 171322FF
  border:
    bottom-width: 1
    color: 211C2EFF
  left:
    - i3:
        sort: ascending
        strip-workspace-numbers: true
        anchors:
          - string: &default {margin: 8, text: "{name}",font: *icon}
          - focused: &focused
              foreground: F9F9F9FF
        content:
          "":
            map:
              conditions:
                state == focused:   {string: {<<: [*default, *focused]}}
                state == unfocused: {string: {<<: *default}}
                state == invisible: {string: {<<: *default}}
          current:
            map:
              conditions:
                mode == "default":
                  - {empty: {}}
                mode == "resize":
                  - string: {left-margin: 5, text: 󰩨, font: *icon, foreground: E69200FF}
                mode == "capture":
                  - string: {left-margin: 5, text: 󰻃, font: *icon, foreground: 42AED5FF}
                mode == "music":
                  - string: {left-margin: 5, text: 󰗅, font: *icon, foreground: 10E080FF}
                mode == "power":
                  - string: {left-margin: 5, on-click: "swaymsg exit", text: 󰗼, font: *icon, foreground: FF427CFF}
                  - string: {left-margin: 10, on-click: "loginctl reboot", text:  , font: *icon, foreground: FF427CFF}
                  - string: {left-margin: 10, on-click: "loginctl poweroff", text:   , font: *icon, foreground: FF427CFF}
    - mpd:
        host: 127.0.0.1
        port: 6600
        content:
          - string: {text: "{title} {pos}/{end}",left-margin: 5}
  right:
    - network:
        name: wlp1s0
        poll-interval: 1000
        content:
          map:
            default: {string: {text:  , font: *icon, foreground: F9F9F9FF}}
            conditions:
              state == down: {string: {text: 󰖪 , font: *icon}}
              state == up:
                - string: {text: "{ssid}",right-margin: 5}
                - string: {text:  ,font: *icon}
    - pipewire:
        anchors:
          volume: &volume
            conditions:
              muted: {string: {text: " {cubic_volume}%",right-margin: 5}}
              ~muted: {string: {text: " {cubic_volume}%",right-margin: 5}}
        content:
          list:
            items:
              - map:
                  <<: *volume
              - map:
                  on-click: "foot -a mixer pulsemixer"
                  conditions:
                    type == "sink":
                      map:
                        conditions:
                          muted: {string: {text: 󰝟 ,font: *icon}}
                          ~muted: 
                            - ramp:
                                tag: cubic_volume
                                items:
                                  - string: {text:   ,font: *icon}
                                  - string: {text:   ,font: *icon}
                                  - string: {text: 󰕾  ,font: *icon}
                                  - string: {text:   ,font: *icon}
                    type == "source":
                      map:
                        conditions:
                          muted: {string: {text:  ,font: *icon}}
                          ~muted: {string: {text:  ,font: *icon}}
    - cpu:
        content:
          map:
            conditions:
              id < 0:
                - string: {text: "{cpu}%",right-margin: 5}
                - string: {text:  , font: *icon}
    - mem:
          content:
            - string: {text: "{used:mb} MB",right-margin: 5}
            - string: {text:  ,font: *icon}
    - backlight:
        name: amdgpu_bl0
        content: 
          - string: {text: "{percent}%",right-margin: 5}
          - ramp:
              tag: brightness
              items:
                - string: {text: 󱩏 , font: *icon}
                - string: {text: 󱩐 , font: *icon}
                - string: {text: 󱩓 , font: *icon}
                - string: {text: 󱩔 , font: *icon}
                - string: {text: 󱩕 , font: *icon}
                - string: {text: 󱩖 , font: *icon}
                - string: {text: 󰛨 , font: *icon, foreground: F9F9F9FF}
    - battery:
        name: BAT0
        poll-interval: 500
        anchors:
          discharging: &discharging
            list:
              items:
                - string: {text: "{capacity}%",right-margin: 5}
                - ramp:
                    tag: capacity
                    items:
                      - string: {text:  , font: *icon}
                      - string: {text:  , font: *icon} 
                      - string: {text:  , font: *icon} 
                      - string: {text:  , font: *icon} 
                      - string: {text:  , font: *icon} 
        content:
          map:
            conditions:
              state == unknown:
                <<: *discharging
              state == discharging:
                <<: *discharging
              state == charging:
                - string: {text: "{capacity}%",right-margin: 5}
                - string: {text:  , font: *icon}
              state == full:
                - string: {text: "{capacity}%",right-margin: 5}
                - string: {text:  , font: *icon, foreground: 32ED4FFF}
              state == "not charging":
                <<: *discharging
    - clock:
        time-format: "%H:%M"
        content:
          - string: {text: "{time}",margin: 5}
          - string: {text:  , font: *icon,right-margin: 6}
          - string: {text: "{date}",right-margin: 5}
          - string: {text:  , font: *icon,right-margin: 12}
