local c = require('core.coloring.palette')

local chadtree_settings = {
	['keymap'] =  { 
		['bigger'] = {'+'},
		['change_dir'] =  {b},
              	['clear_filter'] =  {F},
              	['clear_selection'] =  {S},
              	['collapse'] =  {'<s-tab>'},
              	['copy'] =  {p},
              	['copy_basename'] =  {Y},
              	['copy_name'] =  {y},
              	['copy_relname'] =  {'<c-y>'},
              	['cut'] =  {x},
              	['delete'] =  {d},
              	['filter'] =  {f},
              	['h_split'] =  {W},
              	['jump_to_current'] =  {J},
              	['new'] =  {a},
              	['open_sys'] =  {o},
              	['primary'] =  {'<enter>'},
              	['refresh'] =  {'<c-r>'},
              	['rename'] =  {r},
              	['secondary'] = {'<tab>'},
              	['select'] =  {s},
              	['smaller'] =  {'-'},
              	['stat'] =  {K},
              	['tertiary'] =  {'<m-enter>'},
              	['toggle_follow'] =  {u},
              	['toggle_hidden'] =  {'.'},
              	['toggle_version_control'] =  {g},
              	['trash'] =  {t},
              	['v_split'] =  {w},
	},
	['options'] = {
		['follow'] = False,
		['lang'] = 'en',
		['session'] = False,
		['show_hidden'] = False,
		['version_control'] = True,
	},
	['profiling'] =  False,
	['theme'] =  { ['discrete_colour_map'] = { 
		['black'] = 'c.bl1',
        	['blue'] = 'c.bu1',
        	['bright_black'] = c.bl0,
        	['bright_blue'] = c.bu0,
        	['bright_cyan'] = c.cy0,
        	['bright_green'] =  c.gr0,
        	['bright_magenta'] = c.lg0,
        	['bright_red'] =  c.rd0,
        	['bright_white'] = c.wh0,
        	['bright_yellow'] = c.yw0,
        	['cyan'] =  c.cy1,
        	['green'] = c.gr1,
        	['magenta'] =  c.lg1,
        	['red'] =  c.rd1,
        	['white'] =  c.wh1,
        	['yellow'] =  c.yw1 },
		['highlights'] = {
			['bookmarks'] = 'Title',
			['ignored'] =  'Comment',
			['quickfix'] =  'Label',
			['version_control'] =  'Comment'
		},
        	['icon_colour_set'] = 'github',
        	['icon_glyph_set'] = 'devicons',
        	['text_colour_set'] = 'env',
	},
  	['view'] =  { 
		['open_direction'] = 'left',
		['sort_by'] =  {'is_folder', 'ext', 'file_name'},
        	['time_format'] =  '%Y-%m-%d %H:%M',

        	['width'] =  20,
        	['window_options'] =  { 
			['cursorline'] = True,
        	        ['foldenable'] =  False,
        	        ['number'] =  False,
        	        ['relativenumber'] =  False,
        	        ['signcolumn'] =  'no',
        	        ['winfixwidth'] =  True,
        	        ['wrap'] =  False,
		},
	},
	['xdg'] =  False,
}
--
vim.api.nvim_set_var("chadtree_settings", chadtree_settings)
